# Generated by Django 5.2.6 on 2026-09-21 20:24

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Organizador',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=150)),
                ('identidad_externa', models.CharField(blank=True, max_length=255, null=True, unique=True)),
                ('limite_diario_horas', models.DecimalField(decimal_places=1, default=6.0, max_digits=4)),
                ('creado_en', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'organizador',
            },
        ),
        migrations.CreateModel(
            name='Evento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=200)),
                ('tipo', models.CharField(choices=[('boda', 'Boda'), ('social', 'Social'), ('corporativo', 'Corporativo'), ('cumpleanos', 'Cumpleaños'), ('otro', 'Otro')], max_length=20)),
                ('cliente_contacto', models.CharField(max_length=255)),
                ('fecha_hora_evento', models.DateTimeField()),
                ('lugar', models.CharField(max_length=255)),
                ('plazo_limite', models.DateField()),
                ('creado_en', models.DateTimeField(auto_now_add=True)),
                ('actualizado_en', models.DateTimeField(auto_now=True)),
                ('organizador', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='eventos', to='api.organizador')),
            ],
            options={
                'db_table': 'evento',
            },
        ),
        migrations.CreateModel(
            name='SubtareaLogistica',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=200)),
                ('fecha_objetivo', models.DateField()),
                ('horas_estimadas', models.DecimalField(decimal_places=1, max_digits=5)),
                ('estado', models.CharField(choices=[('PENDIENTE', 'Pendiente'), ('EJECUTADA', 'Ejecutada'), ('POSPUESTA', 'Pospuesta')], default='PENDIENTE', max_length=10)),
                ('nota_posposicion', models.TextField(blank=True, null=True)),
                ('creado_en', models.DateTimeField(auto_now_add=True)),
                ('actualizado_en', models.DateTimeField(auto_now=True)),
                ('evento', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='subtareas', to='api.evento')),
            ],
            options={
                'db_table': 'subtarea_logistica',
            },
        ),
    ]
